apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2600"
  name: rancher-monitoring-merge
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchLabels:
                  environmentId: dev
                matchExpressions:
                  - key: clusterId
                    operator: NotIn
                    values:
                      - vcluster-10
                      - in-cluster-local
              values:
                path: rancher-monitoring/19.0.3
          - clusters:
              selector:
                matchLabels:
                  bu: ip
              values:
                path: rancher-monitoring/19.0.3
          - list:
              elements:
                - name: vcluster-15
                  url: ''
                  values:
                    path: rancher-monitoring/19.0.3
  template:
    metadata:
      name: 'rancher-monitoring-me-{{name}}'
      labels:
        appset: rancher-monitoring-merge
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2600"
        version: '{{values.path}}'
    spec:
      project: rancher-monitoring
      source:
        helm:
          fileParameters:
            - path: values.yaml
        repoURL: 'https://github.com/ron1/ron1-rancher-monitoring-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: cattle-monitoring-system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=false
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
